---
# https://www.michaelrigart.be/en/blog/testing-ansible-roles-with-travis-ci.html
# https://github.com/geerlingguy/ansible-role-ansible
language: python
python: "2.7"

addons:
  apt:
    packages:
    - git
    - libgfortran3
    - libsqlite3-dev
    - sqlite3
    - libspatialite-dev
    - spatialite-bin
    - g++
    - libudunits2-0
    - libudunits2-dev
    - libjpeg-dev
    - libx11-dev
    - gcc-4.8

install:
  # Install Ansible.
  - pip install -Iv ansible==1.9.3
  - gcc --version
  - pip install libais

#script:
#  - "ansible-playbook provisioning/site.yml -i provisioning/hosts --syntax-check"
#  - "ansible-playbook provisioning/site.yml -i provisioning/hosts -l localhost --connection=local --sudo -vvvv"
